Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -19,7 +19,7 @@ pipeline {
         sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
       }
     }
-stage('Diagnostics') {
+  stage('Diagnostics') {
     steps {
         sh '''
             echo "Checking Java..."
@@ -28,17 +28,12 @@ stage('Diagnostics') {
             echo "Checking Maven..."
             mvn -version
             
-            echo "Running effective-pom..."
-            # Capture the exit code of the maven command
-            mvn help:effective-pom > effective_pom.xml
-            echo "Maven exit code: $?"
-            
-            echo "Searching for sonar..."
-            grep -i sonar -n effective_pom.xml
-            echo "Grep exit code: $?"
+            echo "Running effective-pom (ignoring failure)..."
+            # Using '|| true' ensures that even if Maven crashes, the pipeline continues
+            mvn help:effective-pom || true
         '''
-    }
-}
+        }
+      }
     stage('Static Code Analysis') {
       environment {
         SONAR_URL = "http://172.17.0.1:9000"
